on:
  push:
    branches:
      - master

jobs:
  ci:
    name: Build and Test
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-node@v2
        with:
          node-version: '14.16.0'
      - run: npm i
      - run: npm --version
      - run: time tar czf /tmp/artifact.tgz node_modules
      - run: docker build -t dclayton .
